### ISSUE TITLE
フィールド名に `_` を2つ含む場合 表示がイタリック表記(斜体)になる

### ISSUE THREAD

**Issue by tadashi-aikawa** [gtfs-jp/GTFS-JP-web#1]
※ Issue管理される予定があるのか分かりませんが、気になったため作成させていただきました

`agency_fare_url` のように `_` を2つ以上含む場合、`_`で囲まれたものがイタリック表記になっています。

middlemanの仕様に詳しくないのですが、markdownの斜体表記と認識されてしまっているように見えます。
(GitHubプレビュー上は正しく表示されていました)

【確認したサイト】
https://www.gtfs.jp/developpers-guide/format-reference.html

![image](https://user-images.githubusercontent.com/9500018/57564841-15ffb100-73ee-11e9-863e-823441a1dfa1.png)

**Comment by kumatira** [comment]
( Issue管理の予定です。ライフサイクルについての明示は整備中です。)

ありがとうございます!
スクリーンショットでご指摘の`agency_fare_url `のように`_`で囲まれている単語が斜体表記と認識されているようです。
markdownエンジンとして利用しているredcarpetの設定を見直してみます。

**Comment by kumatira** [comment]
#10 にて対応したのでクローズします

**Comment by tadashi-aikawa** [comment]
ご対応いただきありがとうございました🙇
