### ISSUE TITLE
静的フォーマットの定義書中の表に不要なカラムがある

### ISSUE THREAD

**Issue by kumatira** [gtfs-jp/GTFS-JP-web#6]
静的フォーマットの定義書には、ファイルごとに定義を表した表が存在します。
https://www.gtfs.jp/developpers-guide/format-reference.html

このうち「GTFS」「申請」のカラムが不要ではないでしょうか。
中身がメンテナンスされた結果なのかも怪しいため削除するのが妥当かと思われます。
原版となる国交省配布のwordファイル → http://www.mlit.go.jp/common/001283245.docx

原版wordのカラム構成
<img width="625" alt="スクリーンショット 2019-05-16 3 13 18" src="https://user-images.githubusercontent.com/32349530/57799128-51e99c00-7789-11e9-8a44-2471c50e9adb.png">

現状のカラム構成
<img width="703" alt="スクリーンショット 2019-05-16 3 14 03" src="https://user-images.githubusercontent.com/32349530/57798876-bb1cdf80-7788-11e9-92d1-a0828ff5d8c9.png">

**Comment by takohei** [comment]
削除しましょう。
元々のExcelファイル上で非表示になっていて、
国交省 平成31年度の議論では存在しないカラムとして議論していました。

**Comment by kumatira** [comment]
#14 にて対応したためクローズします
